### ISSUE TITLE
akka-scala-guice-play

### ISSUE THREAD

**Issue by pocman** [rocketraman/activator-akka-scala-guice#2]
Hi,
I'm trying to test with specs2 some @Named actors in my Play application.
I'm using the `"test" in new WithApplicationLoader {}` context and I did not create an AkkaModule as an actor system is already provided by Play 2.4

My Issue is that I get a NullPointerException when running `system.actorOf(GuiceAkkaExtension(system).props(CountingActor.name))`.

**Comment by rocketraman** [comment]
> My Issue is that I get a NullPointerException

Can you isolate which reference specifically is null?

I've never used Specs2 but is it initializing everything similarly to the example ScalaTest? Note the counter actor is a `lazy val` rather than a regular `val`.

**Comment by rocketraman** [comment]
Closing, no additional information provided by OP.
